# Generated by Django 2.1.7 on 2020-01-08 10:36

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='商品唯一货号')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('goods_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存数')),
                ('market_price', models.FloatField(default=0, verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0, verbose_name='本店价格')),
                ('goods_brief', models.TextField(help_text='商品简短描述', max_length=500, verbose_name='商品简短描述')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', help_text='商品内容', verbose_name='内容')),
                ('ship_free', models.BooleanField(default=True, verbose_name='是否承担运费')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/goods/images/', verbose_name='封面图')),
                ('show_type', models.BooleanField(choices=[(0, '常规展示'), (1, '首页轮播'), (2, '最新热点'), (3, '最新活动')], default=0, verbose_name='展示控制')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别标题')),
                ('code', models.CharField(max_length=30, verbose_name='类别编码')),
                ('icon', models.ImageField(upload_to='category/icon/', verbose_name='类别图标')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品类别管理',
                'verbose_name_plural': '商品类别管理',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
