# Generated by Django 2.1.7 on 2020-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='展示顺序'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category/icon/', verbose_name='类别图标'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='类别名称'),
        ),
    ]
