# Generated by Django 2.1.7 on 2020-01-09 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200108_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleShopNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='show_type',
            field=models.BooleanField(choices=[(0, '常规展示'), (1, '首页轮播'), (2, '最新活动')], default=0, verbose_name='展示控制'),
        ),
    ]
