# Generated by Django 2.1.7 on 2020-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200109_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='show_type',
            field=models.IntegerField(choices=[(1, '首页轮播'), (2, '最新活动')], default=1, verbose_name='展示控制'),
        ),
    ]
