# Generated by Django 2.1.7 on 2020-01-08 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='utype',
            field=models.CharField(choices=[('members', '会员'), ('admin', '管理员')], default='members', max_length=50, verbose_name='用户类型'),
        ),
    ]
