# Generated by Django 2.1.7 on 2020-01-09 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200108_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', help_text='省份', max_length=100, verbose_name='省份')),
                ('city', models.CharField(default='', help_text='城市', max_length=100, verbose_name='城市')),
                ('district', models.CharField(default='', help_text='区域', max_length=100, verbose_name='区域')),
                ('address', models.CharField(default='', help_text='详细地址', max_length=100, verbose_name='详细地址')),
                ('signer_name', models.CharField(default='', help_text='签收人', max_length=100, verbose_name='签收人')),
                ('signer_mobile', models.CharField(default='', help_text='电话', max_length=11, verbose_name='电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
    ]
